### ISSUE TITLE
[Exception][New-WebRequest][169]:The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by webframp** [nccgroup/azucar#6]
I'm seeing a lot of 400 Bad Request errors, is this expected? Any pointers how to debug?

<img width="846" alt="screen shot 2018-09-07 at 17 00 19" src="https://user-images.githubusercontent.com/774378/45242838-8e422f80-b2bf-11e8-994f-6f6213722082.png">

**Comment by timothyleung1** [comment]
same here

**Comment by timothyleung1** [comment]
I think im getting an error because the $ObjectDisplayName is empty 
![screen shot 2018-12-27 at 3 29 18 pm](https://user-images.githubusercontent.com/42724530/50465602-4e2cc700-09ec-11e9-943c-fac5edd3eb29.png)

Most likely its because your account do not have access privielge and try to read it out. Since you cant read it, the API call will be malformed, and getting 400 bad request.

**Comment by silverhack** [comment]
Hi all, 
Agree with @timothyleung1  Some of the Azure API has a vague documentation. You can receive these errors if for example you are attempting to access to an empty object. 

I'm still working on that ;)
